/*
 * simple blog
 *
 * A Simple Blog
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package table

import (
	"log"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//

	"github.com/boltdb/bolt"
)

func buildTable() {
	db, err := bolt.Open("my.db", 0600, nil)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	err = db.Update(func(tx *bolt.Tx) error {
		//判断要创建的表是否存在
		b := tx.Bucket([]byte("User"))
		if b == nil {
			//创建叫"MyBucket"的表
			_, err := tx.CreateBucket([]byte("User"))
			if err != nil {

				//插入原始数据
				err := b.Put([]byte("mahuan"), []byte("123"))
				err = b.Put([]byte("mahh"), []byte("1212"))

				if err != nil {
					log.Fatal(err)
				}
			}
		}
		//一定要返回nil
		return nil
	})

	//更新数据库失败
	if err != nil {
		log.Fatal(err)
	}
}
