/*
 * simple blog
 *
 * A Simple Blog
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	sw "github.com/homework/Server/go"

	t "github.com/homework/Server/t"
)

func main() {
	log.Printf("Server started")
	t.CreateUser()
	t.DBTestArticle()
	t.DBTestComment()

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
