/*
 * simple blog
 *
 * A Simple Blog
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"fmt"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//

	"github.com/boltdb/bolt"
)

func test() {
	db, err := bolt.Open("my.db", 0600, nil)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	//create
	err = db.Update(func(tx *bolt.Tx) error {
		b := tx.Bucket([]byte("Comment"))
		//b := tx.Bucket([]byte("date"),[]byte("Content"),[]byte("Author"),[]byte("ArticleId"))

		//create table "xx" if not exits
		if b != nil {

			//insert rows

			err := b.Put([]byte("2019/12/1"), []byte("hello world"),[]byte("ailsa"),byte(1))
			err = b.Put([]byte("2019/12/2"), []byte("hhhh hello world"),[]byte("sasa"),byte(1))
			err = b.Put([]byte("2019/12/2"), []byte("hello world"),[]byte("ailsa"),byte(1))



			if err != nil {
				log.Fatal(err)
				log.Panic("数据存储失败......")
			}
		}
		return nil
	})

	if err != nil {
		log.Fatal(err)
	}

	// 查看数据
	err = db.View(func(tx *bolt.Tx) error {
 
		// 获取BlockBucket表对象
		b := tx.Bucket([]byte("Comment"))
 
		// 往表里面存储数据
		if b != nil {
			content := b.Get([]byte("hhhhhh"))
			fmt.Printf("%s\n",content)
			content = b.Get([]byte("2019/12/0  hhhhhhh"))
			fmt.Printf("%s\n",content)
		}
 
		// 返回nil，以便数据库处理相应操作
		return nil
	})
	//更新失败
	if err != nil {
		log.Panic(err)
	}

}
