/*
 * simple blog
 *
 * A Simple Blog
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package t

import (
	"fmt"
	"log"
	"strconv"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//

	"github.com/boltdb/bolt"
)

func CreateUser() {
	db, err := bolt.Open("my.db", 0600, nil)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	err = db.Update(func(tx *bolt.Tx) error {
		b := tx.Bucket([]byte("User"))
		if b == nil {
			//create table "xx" if not exits
			b, err = tx.CreateBucket([]byte("User"))
			if err != nil {
				log.Fatal(err)
			}
		}

		//insert rows
		for i := 0; i < 10; i++ {
			err := b.Put([]byte("user"+strconv.Itoa(i)), []byte("pass"+strconv.Itoa(i)))
			if err != nil {
				log.Fatal(err)
			}
			fmt.Println("user"+strconv.Itoa(i), "pass"+strconv.Itoa(i))
		}

		return nil
	})

	if err != nil {
		log.Fatal(err)
	}
}
